name: Test
on: 
  push:
  workflow_dispatch:
    inputs:
      branch:
        required: false
        type: string
        default: master

jobs:
  test:
    name: Test
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
    runs-on: ${{ matrix.python == 3.6 && 'ubuntu-20.04' || 'ubuntu-latest' }}

    steps:
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          text: ${{ github.event.inputs.branch }}
          regex: '^[a-zA-Z0-9_/\-]+$'
      - name: Break on invalid branch name
        run: exit 1
        if: ${{ github.event_name == 'workflow_dispatch' && steps.regex-match.outputs && steps.regex-match.outputs.match == '' }}
      - uses: actions/checkout@v3
      - name: Install Python 3.7 manually (if missing)
        if: ${{ matrix.python == 3.7 }}
        run: |
          sudo apt update
          sudo apt install -y python3.7 python3.7-dev python3.7-distutils
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
          sudo apt install -y python3-pip
          python3 -m pip install --upgrade pip
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: v1/${{ runner.os }}/pypi-${{matrix.python}}/${{ hashFiles('{requirements,development}.txt') }}
          restore-keys: v1/${{ runner.os }}/pypi-${matrix.python}/
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: v1/${{ runner.os }}/node-${{ matrix.node }}/${{ hashFiles('**/yarn.lock') }}
          restore-keys: v1/${{ runner.os }}/node-${{ matrix.node }}/
      - name: Set up @percy/cli from git
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          cd /tmp
          git clone --branch ${{ github.event.inputs.branch }} --depth 1 https://github.com/percy/cli
          cd cli
          PERCY_PACKAGES=`find packages -mindepth 1 -maxdepth 1 -type d | sed -e 's/packages/@percy/g' | tr '\n' ' '`
          git log -1
          yarn
          yarn build
          yarn global:link
          cd ${{ github.workspace }} 
          yarn remove @percy/cli && yarn link `echo $PERCY_PACKAGES`
          npx percy --version
       
      - run: make test
